name: disk_space
description: A Flutter plugin for retrieving total, free and used disk space.
version: 0.2.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.disk_space
        pluginClass: DiskSpacePlugin
      ios:
        pluginClass: DiskSpacePlugin
